# Generated by Django 2.0 on 2018-03-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('IMONumber', models.IntegerField(null=True)),
                ('Shiptype', models.IntegerField(choices=[(1, 'LNG SHIP'), (2, 'OIL TANKER '), (3, 'CHEMICAL TANKER'), (4, 'LPG TANKER'), (5, 'CONTAINER SHIP')], null=True)),
            ],
        ),
    ]
