# Generated by Django 2.0 on 2018-03-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0002_auto_20180316_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship_shore_compatibility',
            name='code_name',
            field=models.CharField(blank=True, help_text='Code name of the vessel in particular jetty', max_length=100, null=True),
        ),
    ]
