# Generated by Django 2.0 on 2018-03-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0003_ship_shore_compatibility_code_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jetty',
            name='name',
            field=models.CharField(db_index=True, default='', help_text='Name of the jetty', max_length=100, unique=True),
        ),
    ]
