# Generated by Django 2.0 on 2018-03-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0005_auto_20180316_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='bog_guarantee',
            field=models.DecimalField(decimal_places=5, default=0, help_text='BOG guarantee', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ship_shore_compatibility',
            name='sscl_doc',
            field=models.FileField(upload_to='sscs/'),
        ),
    ]
