# Generated by Django 2.0.3 on 2018-07-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0007_auto_20180717_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship_shore_compatibility',
            name='jetty',
        ),
        migrations.RemoveField(
            model_name='ship_shore_compatibility',
            name='ship',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='sscs',
        ),
        migrations.DeleteModel(
            name='Ship_Shore_Compatibility',
        ),
    ]
