# Generated by Django 2.0.3 on 2018-09-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_sales_contract_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_contract',
            name='buyers',
            field=models.ManyToManyField(related_name='as_buyers', related_query_name='as_buyer', to='home.Company'),
        ),
        migrations.AlterField(
            model_name='sales_contract',
            name='sellers',
            field=models.ManyToManyField(related_name='as_sellers', related_query_name='as_seller', to='home.Company'),
        ),
    ]
