# Generated by Django 2.0.3 on 2018-07-24 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ships', '0008_auto_20180723_1232'),
        ('portfolios', '0001_initial'),
        ('terminals', '0006_auto_20180723_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voyage_number', models.CharField(default='', help_text='Voyage Number or Similar', max_length=100)),
                ('status', models.CharField(choices=[('0', 'Plan'), ('1', 'History')], default='0', max_length=100)),
                ('volume', models.DecimalField(blank=True, decimal_places=5, help_text='Volume on Ship', max_digits=10, null=True)),
                ('loaded_volume', models.DecimalField(blank=True, decimal_places=5, help_text='Volume Loaded', max_digits=10, null=True)),
                ('discharge_volume', models.DecimalField(blank=True, decimal_places=5, help_text='Volume Dischaged', max_digits=10, null=True)),
                ('departure', models.DateTimeField(help_text='Date and time of departure from origin')),
                ('arrival', models.DateTimeField(help_text='Date and time of arrival at destination')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_destination', to='terminals.Jetty')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_origin', to='terminals.Jetty')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ships.Ship')),
                ('transaction', models.ManyToManyField(to='portfolios.Transaction')),
            ],
        ),
    ]
