# Generated by Django 2.0.3 on 2018-07-25 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='transaction',
        ),
    ]
