# Generated by Django 2.0.3 on 2018-08-27 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_auto_20180725_2159'),
        ('terminals', '0006_auto_20180723_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Name of the storage facility', max_length=100)),
                ('operator', models.ManyToManyField(help_text='Operator of the terminal', related_name='as_storage_operator', to='home.Company')),
                ('owner', models.ManyToManyField(help_text='Owner of the terminal', related_name='as_storage_owner', to='home.Company')),
                ('terminal', models.ManyToManyField(help_text='Link to the terminal that it served', to='terminals.Terminal')),
            ],
        ),
        migrations.CreateModel(
            name='Storage_Arrangement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Code name of the vessel in particular jetty', max_length=100)),
                ('capacity', models.DecimalField(decimal_places=2, help_text='100% Capacity in cubic meter', max_digits=20, null=True)),
                ('max_inventory', models.DecimalField(decimal_places=2, help_text='Maximum allowable inventory in tank in cubic meter', max_digits=20, null=True)),
                ('min_inventory', models.DecimalField(decimal_places=2, help_text='Minimum allowable inventory in tank in cubic meter', max_digits=20, null=True)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storages.Storage')),
            ],
        ),
        migrations.AddField(
            model_name='storage_arrangement',
            name='grade_0',
            field=models.ManyToManyField(related_name='_storage_arrangement_grade_0_+', to='storages.Tank'),
        ),
        migrations.AddField(
            model_name='storage_arrangement',
            name='grade_1',
            field=models.ManyToManyField(related_name='_storage_arrangement_grade_1_+', to='storages.Tank'),
        ),
        migrations.AddField(
            model_name='storage_arrangement',
            name='grade_2',
            field=models.ManyToManyField(related_name='_storage_arrangement_grade_2_+', to='storages.Tank'),
        ),
        migrations.AddField(
            model_name='storage_arrangement',
            name='grade_3',
            field=models.ManyToManyField(related_name='_storage_arrangement_grade_3_+', to='storages.Tank'),
        ),
        migrations.AddField(
            model_name='storage_arrangement',
            name='grade_4',
            field=models.ManyToManyField(related_name='_storage_arrangement_grade_4_+', to='storages.Tank'),
        ),
        migrations.AddField(
            model_name='storage_arrangement',
            name='grade_5',
            field=models.ManyToManyField(related_name='_storage_arrangement_grade_5_+', to='storages.Tank'),
        ),
        migrations.AddField(
            model_name='storage_arrangement',
            name='grade_6',
            field=models.ManyToManyField(related_name='_storage_arrangement_grade_6_+', to='storages.Tank'),
        ),
        migrations.AddField(
            model_name='storage_arrangement',
            name='grade_7',
            field=models.ManyToManyField(related_name='_storage_arrangement_grade_7_+', to='storages.Tank'),
        ),
        migrations.AddField(
            model_name='storage_arrangement',
            name='grade_8',
            field=models.ManyToManyField(related_name='_storage_arrangement_grade_8_+', to='storages.Tank'),
        ),
        migrations.AddField(
            model_name='storage_arrangement',
            name='grade_9',
            field=models.ManyToManyField(related_name='_storage_arrangement_grade_9_+', to='storages.Tank'),
        ),
        migrations.AddField(
            model_name='storage_arrangement',
            name='next_arrangement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='storages.Storage_Arrangement'),
        ),
        migrations.AddField(
            model_name='storage_arrangement',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storages.Storage'),
        ),
    ]
