# Generated by Django 2.0.3 on 2018-07-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0003_auto_20180717_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='jetty',
            name='max_ship_length',
            field=models.FloatField(blank=True, help_text='Maximum Length of Vessel that can berth in meters', null=True),
        ),
    ]
