# Generated by Django 2.0.3 on 2018-07-18 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0004_jetty_max_ship_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='jetty',
            name='max_ship_draft',
            field=models.FloatField(blank=True, help_text='Maximum Draft Allowed for a Vessel Berth on this Jetty in meters', null=True),
        ),
        migrations.AddField(
            model_name='jetty',
            name='min_ship_length',
            field=models.FloatField(blank=True, help_text='Minimum Length of Vessel that can berth in meters', null=True),
        ),
        migrations.AddField(
            model_name='jetty',
            name='terminal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='terminals.Terminal'),
            preserve_default=False,
        ),
    ]
