# Generated by Django 2.0.3 on 2018-07-23 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0008_auto_20180723_1232'),
        ('terminals', '0005_auto_20180718_0357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship_Shore_Compatibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sscs_doc', models.FileField(upload_to='sscs/')),
                ('sscs_date_time', models.DateField(auto_now=True, help_text='Date of SSCS')),
                ('code_name', models.CharField(blank=True, help_text='Code name of the vessel in particular jetty', max_length=100, null=True)),
                ('jetty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminals.Jetty')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ships.Ship')),
            ],
        ),
        migrations.AddField(
            model_name='jetty',
            name='sscs',
            field=models.ManyToManyField(through='terminals.Ship_Shore_Compatibility', to='ships.Ship'),
        ),
    ]
