# Generated by Django 2.0.3 on 2018-09-23 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180725_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Company'),
        ),
    ]
