# Generated by Django 2.0.3 on 2018-08-27 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_auto_20180725_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquefaction_Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Name of the storage facility', max_length=100)),
                ('operator', models.ManyToManyField(help_text='Operator of the terminal', related_name='as_liquefaction_facility_operator', to='home.Company')),
                ('owner', models.ManyToManyField(help_text='Owner of the terminal', related_name='as_liquefaction_facility_owner', to='home.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Liquefaction_Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Code name of the vessel in particular jetty', max_length=100)),
                ('capacity', models.DecimalField(decimal_places=2, help_text='100% Capacity in cubic meter', max_digits=20, null=True)),
                ('liquefaction_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquefaction_facilities.Liquefaction_Facility')),
            ],
        ),
    ]
