# Generated by Django 2.0.3 on 2018-08-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('liquefaction_facilities', '0001_initial'),
        ('storages', '0001_initial'),
        ('terminals', '0006_auto_20180723_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquefaction_facility',
            name='storage',
            field=models.ManyToManyField(help_text='Link to the storage', to='storages.Storage'),
        ),
        migrations.AddField(
            model_name='liquefaction_facility',
            name='terminal',
            field=models.ManyToManyField(help_text='Link to the terminal that it served', to='terminals.Terminal'),
        ),
    ]
